development:
  VK_APP_ID: 111111
  VK_APP_SECRET: "111111111111111111"
  VK_APP_HOST: "localhost"
  VK_API_URL: "https://api.vkontakte.ru/method"
  VK_AUTH_URL: "http://oauth.vkontakte.ru/authorize"
  VK_TOKEN_URL: "https://oauth.vkontakte.ru/access_token"
  VK_GROUP_ID: "some_group"